replicaCount: 1

image:
  repository: pkonieczny321/sw-movie-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    port: 80
    targetPort: 3000
    nodePort: 32001

mongodb:
  image: mongo
  port: 27017
  persistence:
    enabled: false